export const screensList = {
  Home: { label: 'Home', title: 'Home' },
  Wallet: { label: 'Wallet', title: 'Wallet' },
  WalletCreate: { label: 'WalletCreate', title: 'Create Wallet' },
  WalletImport: { label: 'WalletImport', title: 'Import Wallet' },
  ImportViaPrivate: { label: 'ImportViaPrivate', title: 'Import Wallet via Address' },
  ScanQRCode: { label: 'ScanQRCode', title: 'Scan QR Code' },
  Unlock: { label: 'Unlock', title: 'Unlock Screen' },
  Transactions: { label: 'Transactions', title: 'Transactions' },
  PasswordSetting: { label: 'PasswordSetting', title: 'Setting Password' },
  AccountSetting: { label: 'AccountSetting', title: 'Account Settings' },
  Settings: { label: 'Settings', title: 'Settings' },
  About: { label: 'About', title: 'About' },
  ChatList: { label: 'ChatList', title: 'Genesis Space' },
  Start: { label: 'Start', title: 'Start' },
  CreateAccount: { label: 'CreateAccount', title: 'Create Account' },
  VerifyCredential: { label: 'VerifyCredential', title: 'Verify Phone' },
  SetPassword: { label: 'SetPassword', title: 'Set Password' },
  ContinueLogin: { label: 'ContinueLogin', title: 'Continue Login' },
  Login: { label: 'Login', title: 'Login' },
  Topic: { label: 'Topic', title: 'Topic' },
  TopicInfo: { label: 'TopicInfo', title: 'Topic Info' },
  Members: { label: 'Members', title: 'All members' },
  MemberInfo: { label: 'MemberInfo', title: 'Member Info' },
  RulesDescription: { label: 'RulesDescription', title: 'RulesDescription' },
};
