export const screensList = {
  Home: { label: 'Home', title: 'Home' },
  Wallet: { label: 'Wallet', title: 'Wallet' },
  WalletCreate: { label: 'WalletCreate', title: 'Create Wallet' },
  WalletImport: { label: 'WalletImport', title: 'Import Wallet' },
  ImportViaPrivate: { label: 'ImportViaPrivate', title: 'Import Wallet via PrivateKey' },
  ImportViaMnemonic: { label: 'ImportViaMnemonic', title: 'Import Wallet via Mnemonic Phrase' },
  ScanQRCode: { label: 'ScanQRCode', title: 'Scan QR Code' },
  Unlock: { label: 'Unlock', title: 'Unlock Screen' },
  Transactions: { label: 'Transactions', title: 'Transactions' },
  PasswordSetting: { label: 'PasswordSetting', title: 'Setting Password' },
  AccountSetting: { label: 'AccountSetting', title: 'Account Settings' },
  Settings: { label: 'Settings', title: 'Settings' },
  About: { label: 'About', title: 'About' },
  ChatList: { label: 'ChatList', title: 'Genesis Space' },
  Start: { label: 'Start', title: 'Start' },
  CreateAccount: { label: 'CreateAccount', title: 'Create Account' },
  VerifyCredential: { label: 'VerifyCredential', title: 'Verify Phone' },
  SetPassword: { label: 'SetPassword', title: 'Set Password' },
  Login: { label: 'Login', title: 'Login' },
  Topic: { label: 'Topic', title: 'Topic' },
  TopicInfo: { label: 'TopicInfo', title: 'Topic Info' },
  Members: { label: 'Members', title: 'All members' },
  MemberInfo: { label: 'MemberInfo', title: 'Member Info' },
  RulesDescription: { label: 'RulesDescription', title: 'RulesDescription' },
  Treasure: { label: 'Treasure', title: 'Treasure' },
  TopicRules: { label: 'TopicRules', title: 'Rules' },
  MemberRules: { label: 'MemberRules', title: 'Member Rules' },
  RulesInfo: { label: 'RulesInfo', title: 'Rules Info' },
  StartVote: { label: 'StartVote', title: 'Start a Vote' },
  AmendSupport: { label: 'AmendSupport', title: 'Amend Support' },
  AmendDuration: { label: 'AmendDuration', title: 'Amend Duration' },
  AmendCost: { label: 'AmendCost', title: 'Amend Cost' },
  AmendMemberRules: { label: 'AmendMemberRules', title: 'Amend Member Rule' },
  AmendCountryName: { label: 'AmendCountryName', title: 'Amend Country Name' },
  AmendDescription: { label: 'AmendDescription', title: 'Amend Description' },
  VoteInfo: { label: 'VoteInfo', title: 'Participate a vote' },
  UploadUserProfile: { label: 'UploadUserProfile', title: 'Upload your profile' },
  UploadCountryProfile: { label: 'UploadCountryProfile', title: 'Upload country profile' },
  CreateTopic: { label: 'CreateTopic', title: 'Create a country' },
  AppStore: { label: 'AppStore', title: 'App Store' },
  AppProfile: { label: 'AppProfile', title: 'App Profile' },
};
